# Site settings
name: Grubbin With Griff
email: GrubbinWithGriff@gmail.com
url: https://GrubbinWithGriff.com
description: "The official Grubbin With Griff blog!"
author: "Griffin S."
title: "Grubbin With Griff"
permalink: pretty
baseurl: /

# social
youtube:
  username: GrubbinWithGriff

twitter:
  username: GrubbinWGriff

facebook:
  username: GrubbinWithGriff

instagram:
  username: GrubbinWGriff